export * from "./schema";

export type Category =
  | "Soups"
  | "Salads"
  | "Continental Starters"
  | "Tandoori Starters"
  | "Egg Items"
  | "Platters"
  | "Chinese Starters"
  | "Indian Flavours"
  | "Main Course Veg"
  | "Main Course Non-Veg"
  | "Biryani"
  | "Biryani Family Pack"
  | "Fried Rice"
  | "Noodles"
  | "Indian Rice"
  | "Dal"
  | "Indian Breads"
  | "Pizzas"
  | "Pasta"
  | "Desserts"
  | "Ice Cream"
  | "Beverages";
